// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/welcome/welcome.proto

package welcome

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WelcomeRequest is the request for welcome
type WelcomeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WelcomeRequest) Reset() {
	*x = WelcomeRequest{}
	mi := &file_proto_welcome_welcome_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WelcomeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WelcomeRequest) ProtoMessage() {}

func (x *WelcomeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_welcome_welcome_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WelcomeRequest.ProtoReflect.Descriptor instead.
func (*WelcomeRequest) Descriptor() ([]byte, []int) {
	return file_proto_welcome_welcome_proto_rawDescGZIP(), []int{0}
}

// WelcomeResponse is the response for welcome
type WelcomeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Message        string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Service        string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ProjectVersion string                 `protobuf:"bytes,4,opt,name=project_version,json=projectVersion,proto3" json:"project_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WelcomeResponse) Reset() {
	*x = WelcomeResponse{}
	mi := &file_proto_welcome_welcome_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WelcomeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WelcomeResponse) ProtoMessage() {}

func (x *WelcomeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_welcome_welcome_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WelcomeResponse.ProtoReflect.Descriptor instead.
func (*WelcomeResponse) Descriptor() ([]byte, []int) {
	return file_proto_welcome_welcome_proto_rawDescGZIP(), []int{1}
}

func (x *WelcomeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WelcomeResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *WelcomeResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *WelcomeResponse) GetProjectVersion() string {
	if x != nil {
		return x.ProjectVersion
	}
	return ""
}

var File_proto_welcome_welcome_proto protoreflect.FileDescriptor

const file_proto_welcome_welcome_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/welcome/welcome.proto\x12\awelcome\x1a\x1fgoogle/protobuf/timestamp.proto\"\x10\n" +
	"\x0eWelcomeRequest\"\xa8\x01\n" +
	"\x0fWelcomeResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12'\n" +
	"\x0fproject_version\x18\x04 \x01(\tR\x0eprojectVersion2N\n" +
	"\x0eWelcomeService\x12<\n" +
	"\aWelcome\x12\x17.welcome.WelcomeRequest\x1a\x18.welcome.WelcomeResponseB\x1eZ\x1ccopier/proto/welcome;welcomeb\x06proto3"

var (
	file_proto_welcome_welcome_proto_rawDescOnce sync.Once
	file_proto_welcome_welcome_proto_rawDescData []byte
)

func file_proto_welcome_welcome_proto_rawDescGZIP() []byte {
	file_proto_welcome_welcome_proto_rawDescOnce.Do(func() {
		file_proto_welcome_welcome_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_welcome_welcome_proto_rawDesc), len(file_proto_welcome_welcome_proto_rawDesc)))
	})
	return file_proto_welcome_welcome_proto_rawDescData
}

var file_proto_welcome_welcome_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_welcome_welcome_proto_goTypes = []any{
	(*WelcomeRequest)(nil),        // 0: welcome.WelcomeRequest
	(*WelcomeResponse)(nil),       // 1: welcome.WelcomeResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_proto_welcome_welcome_proto_depIdxs = []int32{
	2, // 0: welcome.WelcomeResponse.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: welcome.WelcomeService.Welcome:input_type -> welcome.WelcomeRequest
	1, // 2: welcome.WelcomeService.Welcome:output_type -> welcome.WelcomeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_welcome_welcome_proto_init() }
func file_proto_welcome_welcome_proto_init() {
	if File_proto_welcome_welcome_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_welcome_welcome_proto_rawDesc), len(file_proto_welcome_welcome_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_welcome_welcome_proto_goTypes,
		DependencyIndexes: file_proto_welcome_welcome_proto_depIdxs,
		MessageInfos:      file_proto_welcome_welcome_proto_msgTypes,
	}.Build()
	File_proto_welcome_welcome_proto = out.File
	file_proto_welcome_welcome_proto_goTypes = nil
	file_proto_welcome_welcome_proto_depIdxs = nil
}
